### ISSUE TITLE
Error: call revert exception

### ISSUE THREAD

**Issue by orajiakuchibuchi** [pguso/angular-hardhat-starter-dapp#2]
I get this error when trying to read my images from the contract under the image listing page. no image is being displayed
![Screenshot (166)](https://user-images.githubusercontent.com/39632786/154120283-7213de30-4b3d-44b3-bffd-ec11ef8acc62.png)

**Comment by pguso** [comment]
This error is shown when the selected network in Metamask doesn't match the network you deployed your contract to.

For example:
If you deployed your contract via `npm run deploy:testnet` to the polygon mumbai testnet, then the polygon testnet must be selected within Metamask to interact with the contract.

If you give me more details and what you try to achieve I am happy to help you.
